[target.armv7-unknown-linux-musleabihf]
linker = "rust-lld"
rustflags = [
    "-C", "target-cpu=cortex-a7",       # 指定 CPU 即可，会自动应用最匹配的特性
    "-C", "target-feature=+crt-static", 
    "-C", "link-self-contained=yes",     
    "-C", "linker-flavor=ld.lld"         
]
